# fly.toml app configuration file generated for webhooks-server-nylas-testing on 2025-04-24T19:06:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webhooks-server-nylas-testing'
primary_region = 'eze'

[build]
  [build.args]
    GO_VERSION = '1.21'

[env]
  PORT = '8080'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
